[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://angkorcompliance.com/*"
  to = "https://angkorcompliance.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.angkorcompliance.com/*"
  to = "https://angkorcompliance.com/:splat"
  status = 301
  force = true

[build.environment]
  NODE_VERSION = "18" 