# Netlify Configuration for Angkor Compliance
[build]
  publish = "."
  functions = "netlify/functions"
  command = "cd netlify/functions && npm install"
  
# Skip build processing
[build.processing]
  skip_processing = false

# Environment variables
[build.environment]
  SKIP_BUILD = "false"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  
# Authentication API redirects - FIXED ROUTING
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth"
  status = 200
  force = true
  query = {path = "/login"}

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/auth"
  status = 200
  force = true
  query = {path = "/register"}

[[redirects]]
  from = "/api/auth/validate"
  to = "/.netlify/functions/auth"
  status = 200
  force = true
  query = {path = "/validate"}

[[redirects]]
  from = "/api/auth/health"
  to = "/.netlify/functions/auth"
  status = 200
  force = true
  query = {path = "/health"}

# Fallback to server function for other API calls
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:;"

# Headers for API endpoints
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization" 