# Netlify Configuration for Static Site with Functions
[build]
  publish = "."
  
# Skip build processing
[build.processing]
  skip_processing = true

# Ignore package.json build scripts
[build.environment]
  SKIP_BUILD = "true"
  NODE_VERSION = "18"
  
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth/login"
  status = 200

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/auth/register"
  status = 200

[[redirects]]
  from = "/api/auth/health"
  to = "/.netlify/functions/auth/health"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 